### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by adnansh95** [mkapra/dokumentvwsys#7]
to change the logo of login page: in app/views/devise/sessions/new.html.erb change the name of the file and store the logo in /dokumentvwsys/src/dokumentvwsys/public

**Comment by mkapra** [comment]
Maybe we can draw something like this by ourselves?

![dokumentvwsys](https://user-images.githubusercontent.com/34742358/110524648-f2097580-8113-11eb-85c8-78c2549b7ca4.png)

![c910d3fc-95f2-4330-b895-74e39daeeb17_200x200](https://user-images.githubusercontent.com/34742358/110524678-f9c91a00-8113-11eb-9b72-e0a18dd68605.png)
